# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
