# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_streams', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
