# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeSearchFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=40)),
                ('location', models.CharField(default='37.42307,-122.08427', help_text='add latitude, longitude coordinates', max_length=40)),
                ('location_radius', models.CharField(default='20km', help_text='Example: 5mi, 10km', max_length=10)),
                ('max_results', models.PositiveIntegerField(default=25)),
                ('eventType', models.CharField(default='completed', max_length=10)),
                ('order', models.CharField(default='viewCount', max_length=15)),
            ],
        ),
    ]
