# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentCount', models.PositiveIntegerField(default=0)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('videoCount', models.PositiveIntegerField(default=0)),
                ('subscriberCount', models.PositiveIntegerField(default=0)),
                ('googlePlusUserId', models.CharField(blank=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=240, null=True)),
                ('country', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='youtubesearchfilters',
            name='eventType',
        ),
        migrations.RemoveField(
            model_name='youtubesearchfilters',
            name='location',
        ),
        migrations.RemoveField(
            model_name='youtubesearchfilters',
            name='location_radius',
        ),
        migrations.RemoveField(
            model_name='youtubesearchfilters',
            name='max_results',
        ),
    ]
