# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_bot', '0002_auto_20160604_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubedata',
            old_name='commentCount',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='youtubedata',
            old_name='googlePlusUserId',
            new_name='google_plus_user_Id',
        ),
        migrations.RenameField(
            model_name='youtubedata',
            old_name='subscriberCount',
            new_name='subscriber_count',
        ),
        migrations.RenameField(
            model_name='youtubedata',
            old_name='videoCount',
            new_name='video_count',
        ),
        migrations.RenameField(
            model_name='youtubedata',
            old_name='viewCount',
            new_name='view_count',
        ),
    ]
