# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_bot', '0004_auto_20160604_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='is_already_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
