# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_bot', '0005_youtubedata_is_already_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubedata',
            options={'verbose_name': 'view data fetched', 'verbose_name_plural': 'view data fetched'},
        ),
        migrations.AlterModelOptions(
            name='youtubesearchfilters',
            options={'verbose_name': 'add search word', 'verbose_name_plural': 'add search words'},
        ),
    ]
