# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='group_id',
            field=models.CharField(default=260069440751448, max_length=180),
            preserve_default=False,
        ),
    ]
