# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSearchSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_words', models.CharField(max_length=140)),
                ('exclude_words', models.CharField(max_length=140)),
            ],
        ),
    ]
