# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0002_keywordsearchsuggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearchsuggest',
            name='minimum_likes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='keywordsearchsuggest',
            name='minimum_retweets',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='livecodinghandle',
            name='minimum_likes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='livecodinghandle',
            name='minimum_retweets',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
