# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0003_auto_20160530_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecodinghandle',
            name='minimum_likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livecodinghandle',
            name='minimum_retweets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
