# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0005_keywordsearchsuggest_last_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsearchsuggest',
            name='exclude_words',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
