# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0007_livecodinghandle_last_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=240)),
                ('access_token_secret', models.CharField(max_length=240)),
                ('consumer_secret', models.CharField(max_length=240)),
                ('consumer_key', models.CharField(max_length=240)),
            ],
        ),
    ]
