# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0009_auto_20160603_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowFollowersOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=140, unique=True)),
                ('is_accounts_followed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='keywordsearchsuggest',
            options={'verbose_name': 'search word', 'verbose_name_plural': 'search words'},
        ),
        migrations.AlterModelOptions(
            name='livecodinghandle',
            options={'verbose_name': 'search word', 'verbose_name_plural': 'search words'},
        ),
    ]
